DATA:
 DATASET: "kinetics"
 CATEGORY: 400
 NUM_FRAMES: 8
 SAMPLING_RATE: 8
 TRAIN_JITTER_SCALES: [224, 320]
 TRAIN_CROP_SIZE: 224
 TEST_CROP_SIZE: 224
 INPUT_CHANNEL_NUM: [3]
 PATH_TO_DATA_DIR: "/data/Kinetics400_mmlab"
 PATH_PREFIX: "/data/Kinetics400_mmlab"
 PATH_LABEL_SEPARATOR: " "
 MEAN: [0.485, 0.456, 0.406]
 STD: [0.229, 0.224, 0.225]
 #MEAN: [0.5, 0.5, 0.5]
 #STD: [0.5, 0.5, 0.5]
 INPUT_CHANNEL_NUM: [3]
 # If True, revert the default input channel (RBG <-> BGR).
 REVERSE_INPUT_CHANNEL: False
 VFORMAT: "TCHW"

TRAIN:
 LR: 1.0 # LR = 0.97 /(43 * 8) * TRN_BATCH * N_GPUS * 16
 LR_STEPS: [10, 15, 18]
 GRADIENT_ACCUMULATION_STEPS: 10
 CLIP_GD: 1.0
 TRN_BATCH: 15
 VAL_BATCH: 15
 PRECISE_BN: 200
 PBN_EPOCH: 1

TEST:
 NUM_ENSEMBLE_VIEWS: 1 # 1
 NUM_SPATIAL_CROPS: 3

MODEL:
 NET: "MViT"
 BACKBONE: "MViTv2_B"
 FOLD_DIV: 0

MVIT:
  DROPPATH_RATE: 0.3
  DEPTH: 24
  DIM_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  HEAD_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  POOL_KVQ_KERNEL: [3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [4, 4]
  POOL_Q_STRIDE: [[0, 1, 1], [1, 1, 1], [2, 2, 2], [3, 1, 1], [4, 1, 1], [5, 2, 2], [6, 1, 1], [7, 1, 1], [8, 1, 1], [9, 1, 1], [10, 1, 1], [11, 1, 1], [12, 1, 1], [13, 1, 1], [14, 1, 1], [15, 1, 1], [16, 1, 1], [17, 1, 1], [18, 1, 1], [19, 1, 1], [20, 1, 1], [21, 2, 2], [22, 1, 1], [23, 1, 1]]
  CLS_EMBED_ON : True
