DATA:
 DATASET: "kinetics"
 CATEGORY: 400
 NUM_FRAMES: 8
 SAMPLING_RATE: 8
 TRAIN_JITTER_SCALES: [224, 360]
 TRAIN_CROP_SIZE: 224
 TEST_CROP_SIZE: 224
 INPUT_CHANNEL_NUM: [3]
 PATH_TO_DATA_DIR: "/data/Kinetics400_mmlab"
 PATH_PREFIX: "/data/Kinetics400_mmlab"
 PATH_LABEL_SEPARATOR: " "
 MEAN: [0.486, 0.457, 0.407]
 STD: [0.229, 0.224, 0.225]
 #MEAN: [0.5, 0.5, 0.5]
 #STD: [0.5, 0.5, 0.5]
 INPUT_CHANNEL_NUM: [3]
 # If True, revert the default input channel (RBG <-> BGR).
 REVERSE_INPUT_CHANNEL: False
 VFORMAT: "TCHW"

TRAIN:
 LR: 0.2 # LR = 0.97 /(43 * 8) * TRN_BATCH * N_GPUS * 16
 LR_STEPS: [10, 15, 18]
 GRADIENT_ACCUMULATION_STEPS: 10
 CLIP_GD: 1.0
 TRN_BATCH: 40
 VAL_BATCH: 100
 PRECISE_BN: 200
 PBN_EPOCH: 1

TEST:
 NUM_ENSEMBLE_VIEWS: 1 # 1
 NUM_SPATIAL_CROPS: 3

MODEL:
 NET: "Visformer_plain_shift"
 BACKBONE: "visformer_small"
 FOLD_DIV: 4
