DATA:
 DATASET: "kinetics"
 CATEGORY: 400
 NUM_FRAMES: 8
 SAMPLING_RATE: 32
 TRAIN_JITTER_SCALES: [384, 512]
 TRAIN_CROP_SIZE: 384
 TEST_CROP_SIZE: 384
 INPUT_CHANNEL_NUM: [3]
 PATH_TO_DATA_DIR: "/data/Kinetics400_mmlab"
 PATH_PREFIX: "/data/Kinetics400_mmlab"
 PATH_LABEL_SEPARATOR: " "
 #MEAN: [0.486, 0.457, 0.407]
 #STD: [0.229, 0.224, 0.225]
 MEAN: [0.5, 0.5, 0.5]
 STD: [0.5, 0.5, 0.5]
 INPUT_CHANNEL_NUM: [3]
 # If True, revert the default input channel (RBG <-> BGR).
 REVERSE_INPUT_CHANNEL: False
 VFORMAT: "TCHW"

TRAIN:
 LR: 0.05  # LR = 0.1 /42 * TRN_BATCH * N_GPUS
 LR_STEPS: [10, 15, 18]
 GRADIENT_ACCUMULATION_STEPS: 10
 CLIP_GD: 1.0
 TRN_BATCH: 5
 VAL_BATCH: 32 #8

TEST:
 #NUM_ENSEMBLE_VIEWS: 1 # Set when training
 NUM_ENSEMBLE_VIEWS: 1 # Set when evaluaiton
 NUM_SPATIAL_CROPS: 3

MODEL:
 NET: "TokShift"
 BACKBONE: "vit_base_patch16_384"
 FOLD_DIV: 4
